routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');

/**
 * Account
 */
Route::get('account/edit', 'AccountController@edit')->name('account.edit');
Route::patch('account/edit', 'AccountController@update');

/**
 * Filtering
 */
Route::get('forum/filter', 'Forum\FilterController@index');

/**
 * Search threads
 */
Route::get('forum/search', 'Forum\SearchController@index')->name('threads.search');

/**
 * Tag
 */
Route::get('forum/tags', 'Forum\TagController@index');
Route::get('forum/{tag}', 'Forum\TagController@show')->name('tags.show');

/**
 * Thread
 */
Route::get('forum', 'Forum\ThreadController@index')->name('threads');
Route::get('create-new-thread', 'Forum\ThreadController@create')->name('threads.create');
Route::post('create-new-thread', 'Forum\ThreadController@store');
Route::get('forum/{tag}/{thread}', 'Forum\ThreadController@show')->name('threads.show');
Route::get('edit-my-thread-on/{tag}/{thread}', 'Forum\ThreadController@edit')->name('threads.edit');
Route::patch('edit-my-thread-on/{tag}/{thread}', 'Forum\ThreadController@update');
Route::delete('delete-my-thread/{thread}', 'Forum\ThreadController@destroy')->name('threads.delete');

/**
 * Reply
 */
Route::post('reply-on-the-thread/{thread}', 'Forum\ReplyController@store')->name('replies.create');
Route::get('edit-reply-on-the-thread/{thread}/{reply}', 'Forum\ReplyController@edit')->name('replies.edit');
Route::patch('edit-reply-on-the-thread/{thread}/{reply}', 'Forum\ReplyController@update');

/**
 * Answer
 */
Route::patch('mark-as-answer-at-reply/{reply}', 'Forum\AnswerController@store')->name('answer.create');

Route::get('{user}', 'UserController@show')->name('users.show');

app/User.php
<?php

namespace App;
use App\Models\Forum\{Reply, Thread};
use App\Traits\{HasManyReply, HasManyThread};
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasManyReply, HasManyThread;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'hash', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function usernameOrHash()
    {
        return $this->username ?: $this->hash;
    }

    public function avatar($size = 200)
    {
        if (!$this->avatar) {
            return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $this->email ) ) ) . "?d=mm&s=" . $size;
        } else {
            return $this->avatar;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show($user)
    {
        $user = User::withCount('threads')->whereHash($user)->orWhere('username', $user)->firstOrFail();
        $threads = $user->threads()->latest()->paginate(10);
        return view('users.show', compact('threads', 'user'));
    }
}

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title', $user->name)
@section('content')
    <div class="card mb-3">
        <div class="card-body">
            <div class="media">
                <img width="40" height="40" src="{{ $user->avatar() }}" class="mr-3 rounded-circle" style="object-fit: cover; object-position: center;" alt="...">
                <div class="media-body">
                    <div class="mt-0 d-block">{{ $user->name }}</div>
                    <div class="text-secondary">
                        Threads: {{ $user->threads_count }}
                    </div>
                    <div class="text-secondary">
                        Joined: {{ $user->created_at->format("d F Y") }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <a href="{{ route('threads') }}" class="text-secondary">Forum</a>
            @isset ($tag)
                <span class="text-secondary">
                    / {{ $tag->name }}
                </span>
            @endisset
        </div>

        <div class="card-body">
            @foreach ($threads as $thread)
                <div class="row mb-4 d-flex align-items-center">
                    <div class="col-md-10">
                        <div class="media">
                            <div class="media-body">
                                <a href="{{ route('threads.show', [$thread->tag, $thread]) }}" class="mt-0 d-block">{{ $thread->title }}</a>
                                <div class="text-secondary">
                                    {{ Str::limit($thread->body, 120) }}
                                </div>
                                <small class="text-secondary">
                                    <a href="{{ route('users.show', $thread->user) }}" class="text-secondary">{{ $thread->user->name }}</a> posted {{ $thread->created_at->diffForHumans() }}
                                    &middot; {{ $thread->replies_count }} {{ Str::plural('reply', $thread->replies_count) }}
                                </small>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <small>
                            <a href="{{ route('tags.show', $thread->tag) }}" class="text-secondary">{{ $thread->tag->name }}</a>
                        </small>
                    </div>
                </div>
            @endforeach

            {{ $threads->links() }}
        </div>
    </div>
@endsection